version: 1.0

language: node_js

node_js:
  - "12.16.3"

script:
  - npm run build
  - npm run cover

after_script:
  - "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"

cache:
  directories:
    - node_modules

branches:
  only:
    - master