version: 1.0

language: node_js

node_js:
  - "12.16.3"
  - stable

script:
  - npm run build

after_success:
  - npm run test:unit

after_script:

cache:
  directories:
    - node_modules

branches:
  only:
    - master